name: CI
on: [push, pull_request]
#  schedule:
#  - cron: '* 6 * * *'

jobs:
  deepin-wine-qq-arch-build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Build Arch Linux package
        uses: taotieren/build-arch-package@master
        with:
          BUILDING: multilib-build
          PKGBUILD: $GITHUB_WORKSPACE/PKGBUILD
          OUTDIR: $HOME/arch-packages
          
      - name: Prepare deepin-wine-qq
        run: |
          mkdir -p ./artifact/deepin-wine-qq/
          cp -rf $(find $GITHUB_WORKSPACE/ -type f -name "*.sh*") $HOME/arch-packages/
          bash $HOME/arch-packages/gen.sh -m
          cp -rf $(find $HOME/arch-packages -type f -name "*.zst*") ./artifact/deepin-wine-qq/

      - name: Deliver deepin-wine-qq
        uses: actions/upload-artifact@v2
        with:
          name: deepin-wine-qq
          path: ./artifact/deepin-wine-qq/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/deepin-wine-qq/*
          tag: ${{ github.ref }}
          file_glob: true
